### ISSUE TITLE
ObjectId doesnt get resolved

### ISSUE THREAD

**Issue by ma-hack** [darrachequesne/spring-data-mongodb-datatables#2]
Hi,
i have a problem with the datatable result, because the id of the entries is empty.

`{"draw":1,"recordsTotal":4,"recordsFiltered":2,"data":[{"id":{},"assetType":"UCProfile","manufactor":null,"model":null,"name":"06305416641","description":null,"location":null,"phoneNumber":"06305416641","dialingAuthorization":null,"manualDisplayNameEnabled":true,"pickupGroupEnabled":false},{"id":{},"assetType":"UCProfile","manufactor":null,"model":null,"name":"01761546","description":null,"location":null,"phoneNumber":"01761546","dialingAuthorization":null,"manualDisplayNameEnabled":false,"pickupGroupEnabled":true}],"error":null}`

As Id i used the ObjectId datatype.
```
    @JsonView(DataTablesOutput.View.class)
    @Id
    private ObjectId id;
```

When i switch the id to string than the id generation works! Is objectId not supported? How can i fix the problem?

Thank you!

Best regards,
Marco

**Comment by darrachequesne** [comment]
@ma-hack sorry for the delay!

According to https://stackoverflow.com/questions/14012890/jackson-json-deserialization-of-mongodb-objectid, you have to register a custom Jackson serializer for the ObjectId class.

You could also use the `converter` argument of the `findAll(DataTablesInput input, Function<T, R> converter)` method, in order to convert the ObjectId to a plain String.

(but I guess you've found a solution by now :smile_cat: )

**Comment by ma-hack** [comment]
Thank you for reply. I was not aware that I can do it easy with a converter. So, i changed from ObjectId to String for the id.
